version: "3.7"
services:
  web:
    build: .
    volumes:
      - ./project:/var/www/html
    ports:
      - 8080:80

  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: rownmrbo_db_earthquake
    ports:
    - 3306:3306
  
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes: 
      - ./mqtt/config:/mqtt/config
      - ./mqtt/data:/mqtt/data
      - ./mqtt/log:/mqtt/log
    ports: 
      - 1883:1883
      - 9001:9001

